//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Remote.Service.RemoteSearchService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="RemoteSearchService.ISearcher")]
    public interface ISearcher {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearcher/QueryProduct", ReplyAction="http://tempuri.org/ISearcher/QueryProductResponse")]
        string QueryProduct(string keyword);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ISearcher/QueryProduct", ReplyAction="http://tempuri.org/ISearcher/QueryProductResponse")]
        System.Threading.Tasks.Task<string> QueryProductAsync(string keyword);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ISearcherChannel : Remote.Service.RemoteSearchService.ISearcher, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SearcherClient : System.ServiceModel.ClientBase<Remote.Service.RemoteSearchService.ISearcher>, Remote.Service.RemoteSearchService.ISearcher {
        
        public SearcherClient() {
        }
        
        public SearcherClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SearcherClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearcherClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SearcherClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string QueryProduct(string keyword) {
            return base.Channel.QueryProduct(keyword);
        }
        
        public System.Threading.Tasks.Task<string> QueryProductAsync(string keyword) {
            return base.Channel.QueryProductAsync(keyword);
        }
    }
}
